spring.application.name=deploy

spring.datasource.url = jdbc:postgresql://localhost:5432/datajpa
spring.datasource.username = postgres
spring.datasource.password = root

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=${PORT:8080}